# Generated by Django 4.1.6 on 2023-06-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_tracker', '0002_alter_assignment_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='progress',
            field=models.IntegerField(),
        ),
    ]
